trigger:
  - main

pool:
  name: default

stages:
  - stage: Init
    displayName: "Init Stage"
    jobs:
      - job: Init
        steps:
          - script: echo "Initializing Terraform files"
            displayName: "Iniitalize"
      - job: Validate
        steps:
          - script: echo "Validating Terraform files"
            displayName: "Validate"
  - stage: Plan and Apply
    displayName: "Plan and Apply"
    dependsOn: Init
    condition: succeeded()
    jobs:
      - job: Plan
        steps:
          - script: echo "Running Terraform plan"
            displayName: "Terraform plan"
      - job: Apply
        steps:
          - script: echo "Running Terraform apply"
            displayName: "Terraform apply"
  - stage: Destroy
    displayName: "Destroy Remaining Resources"
    jobs:
      - job: Destroy
        steps:
          - script: echo "Running Terraform destroy"
            displayName: "Terraform Destroy"
